"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-30T12:23:09Z).

Frozen, fully expanded cobaya configuration for example2
(source: EXAMPLE_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.19,
    "DES_A1_1": 0.0,
    "DES_A1_2": 0.0,
    "DES_B1_1": 1.42,
    "DES_B1_2": 1.66,
    "DES_B1_3": 1.7,
    "DES_B1_4": 1.62,
    "DES_B1_5": 1.78,
    "DES_B1_6": 1.75,
    "DES_CL_A_LAMBDA": 0.943,
    "DES_CL_BS1": 1.1,
    "DES_CL_BS2": 0.2,
    "DES_CL_B_LAMBDA": 0.207,
    "DES_CL_LNLAMBDA0": 4.26,
    "DES_CL_R0": 30.0,
    "DES_CL_SIGMA_INT": 0.15,
    "DES_DZ_L1": 0.005,
    "DES_DZ_L2": 0.003,
    "DES_DZ_L3": 0.001,
    "DES_DZ_L4": -0.002,
    "DES_DZ_L5": 0.001,
    "DES_DZ_L6": 0.008,
    "DES_DZ_S1": 0.034,
    "DES_DZ_S2": 0.028,
    "DES_DZ_S3": 0.011,
    "DES_DZ_S4": -0.01,
    "DES_M1": 0.0,
    "DES_M2": 0.0,
    "DES_M3": 0.0,
    "DES_M4": 0.0,
    "DES_PM1": 0.0,
    "DES_PM2": 0.0,
    "DES_PM3": 0.0,
    "DES_PM4": 0.0,
    "DES_PM5": 0.0,
    "DES_PM6": 0.0,
    "H0": 69.0,
    "mnu": 0.07719273818983689,
    "ns": 0.96859,
    "omegab": 0.048,
    "omegam": 0.3,
    "w": -1.0,
    "w0pwa": -1.0
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.2
    proposal: 0.2
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.01
    proposal: 0.01
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 3
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.004
    proposal: 0.004
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.015
    proposal: 0.015
    latex: \Omega_\mathrm{m}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
    derived: true
  mnu:
    prior:
      min: 0.06
      max: 0.6
    ref:
      dist: norm
      loc: 0.25
      scale: 0.1
    proposal: 0.05
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
    renames:
    - ombh2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
    renames:
    - omch2
  omegal:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omega_de
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  s8:
    derived: 'lambda sigma8, omegam: sigma8*(omegam/0.3)**0.5'
    latex: S_8
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  yheused:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YHe
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
    derived: true
    renames:
    - omnuh2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\nu}
  DES_DZ_S1:
    prior:
      dist: norm
      loc: 0.034
      scale: 0.018
    ref:
      dist: norm
      loc: 0.034
      scale: 0.018
    proposal: 0.009
    latex: \Delta z_\mathrm{s,DES}^1
  DES_DZ_S2:
    prior:
      dist: norm
      loc: 0.028
      scale: 0.013
    ref:
      dist: norm
      loc: 0.028
      scale: 0.013
    proposal: 0.0065
    latex: \Delta z_\mathrm{s,DES}^2
  DES_DZ_S3:
    prior:
      dist: norm
      loc: 0.011
      scale: 0.006
    ref:
      dist: norm
      loc: 0.011
      scale: 0.006
    proposal: 0.003
    latex: \Delta z_\mathrm{s,DES}^3
  DES_DZ_S4:
    prior:
      dist: norm
      loc: -0.01
      scale: 0.013
    ref:
      dist: norm
      loc: -0.01
      scale: 0.013
    proposal: 0.0065
    latex: \Delta z_\mathrm{s,DES}^4
  DES_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.0
      scale: 0.5
    proposal: 0.75
    latex: A_\mathrm{1-IA,DES}^1
  DES_A1_2:
    prior:
      dist: norm
      loc: 0.0
      scale: 3.0
    ref:
      dist: norm
      loc: 0.0
      scale: 0.5
    proposal: 0.75
    latex: A_\mathrm{1-IA,DES}^2
  DES_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,DES}^3
  DES_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,DES}^4
  DES_A2_1:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^1
  DES_A2_2:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^2
  DES_A2_3:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^3
  DES_A2_4:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^4
  DES_BTA_1:
    value: 1.0
    latex: A_\mathrm{BTA-IA,DES}^1
  DES_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^2
  DES_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^3
  DES_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^4
  DES_M1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.008
    ref:
      dist: norm
      loc: 0.0
      scale: 0.008
    proposal: 0.004
    latex: m_\mathrm{DES}^1
  DES_M2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.013
    ref:
      dist: norm
      loc: 0.0
      scale: 0.013
    proposal: 0.0065
    latex: m_\mathrm{DES}^2
  DES_M3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.009
    ref:
      dist: norm
      loc: 0.0
      scale: 0.009
    proposal: 0.0045
    latex: m_\mathrm{DES}^3
  DES_M4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.012
    ref:
      dist: norm
      loc: 0.0
      scale: 0.012
    proposal: 0.006
    latex: m_\mathrm{DES}^4
  DES_BARYON_Q1:
    value: 0.0
    latex: Q_\mathrm{DES}^1
  DES_BARYON_Q2:
    value: 0.0
    latex: Q_\mathrm{DES}^2
  DES_BARYON_Q3:
    value: 0.0
    latex: Q_\mathrm{DES}^3
  DES_BARYON_Q4:
    value: 0.0
    latex: Q_\mathrm{DES}^4
  DES_DZ_L1:
    prior:
      dist: norm
      loc: 0.005
      scale: 0.007
    ref:
      dist: norm
      loc: 0.005
      scale: 0.007
    proposal: 0.0035
    latex: \Delta z_\mathrm{l,DES}^1
  DES_DZ_L2:
    prior:
      dist: norm
      loc: 0.003
      scale: 0.011
    ref:
      dist: norm
      loc: 0.003
      scale: 0.011
    proposal: 0.0055
    latex: \Delta z_\mathrm{l,DES}^2
  DES_DZ_L3:
    prior:
      dist: norm
      loc: 0.001
      scale: 0.006
    ref:
      dist: norm
      loc: 0.001
      scale: 0.006
    proposal: 0.003
    latex: \Delta z_\mathrm{l,DES}^3
  DES_DZ_L4:
    prior:
      dist: norm
      loc: -0.002
      scale: 0.006
    ref:
      dist: norm
      loc: -0.002
      scale: 0.006
    proposal: 0.003
    latex: \Delta z_\mathrm{l,DES}^4
  DES_DZ_L5:
    prior:
      dist: norm
      loc: 0.001
      scale: 0.01
    ref:
      dist: norm
      loc: 0.001
      scale: 0.01
    proposal: 0.005
    latex: \Delta z_\mathrm{l,DES}^5
  DES_DZ_L6:
    prior:
      dist: norm
      loc: 0.008
      scale: 0.01
    ref:
      dist: norm
      loc: 0.008
      scale: 0.01
    proposal: 0.005
    latex: \Delta z_\mathrm{l,DES}^6
  DES_B1_1:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.42
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^1
  DES_B1_2:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.66
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^2
  DES_B1_3:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.7
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^3
  DES_B1_4:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.62
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^4
  DES_B1_5:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.78
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^5
  DES_B1_6:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.75
      scale: 0.05
    proposal: 0.05
    latex: b_\mathrm{1-DES}^6
  DES_B2_1:
    value: 0.0
    latex: b_\mathrm{2-DES}^1
  DES_B2_2:
    value: 0.0
    latex: b_\mathrm{2-DES}^2
  DES_B2_3:
    value: 0.0
    latex: b_\mathrm{2-DES}^3
  DES_B2_4:
    value: 0.0
    latex: b_\mathrm{2-DES}^4
  DES_B2_5:
    value: 0.0
    latex: b_\mathrm{2-DES}^5
  DES_B2_6:
    value: 0.0
    latex: b_\mathrm{2-DES}^6
  DES_BMAG_1:
    value: -1.57
    latex: b_\mathrm{BMAG-DES}^1
  DES_BMAG_2:
    value: -1.7
    latex: b_\mathrm{BMAG-DES}^2
  DES_BMAG_3:
    value: -0.25
    latex: b_\mathrm{BMAG-DES}^3
  DES_BMAG_4:
    value: 1.5
    latex: b_\mathrm{BMAG-DES}^4
  DES_BMAG_5:
    value: 2.22
    latex: b_\mathrm{BMAG-DES}^5
  DES_BMAG_6:
    value: 2.8
    latex: b_\mathrm{BMAG-DES}^6
  DES_DZ2_L1:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^1
  DES_DZ2_L2:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^2
  DES_DZ2_L3:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^3
  DES_DZ2_L4:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^4
  DES_DZ2_L5:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^5
  DES_DZ2_L6:
    value: 1.0
    latex: \sigma z_\mathrm{l,DES}^6
  DES_PM1:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^1
  DES_PM2:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^2
  DES_PM3:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^3
  DES_PM4:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^4
  DES_PM5:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^5
  DES_PM6:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^6
  DES_CL_LNLAMBDA0:
    prior:
      min: 2.0
      max: 5.0
    ref:
      dist: norm
      loc: 4.26
      scale: 0.05
    proposal: 0.05
    latex: \ln\lambda_{0}
  DES_CL_A_LAMBDA:
    prior:
      min: 0.1
      max: 1.5
    ref:
      dist: norm
      loc: 0.943
      scale: 0.03
    proposal: 0.03
    latex: A_{\ln\lambda}
  DES_CL_SIGMA_INT:
    prior:
      min: 0.1
      max: 1.0
    ref:
      dist: norm
      loc: 0.15
      scale: 0.02
    proposal: 0.02
    latex: \sigma_{\mathrm{int}}
  DES_CL_B_LAMBDA:
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: 0.207
      scale: 0.1
    proposal: 0.1
    latex: B_{\ln\lambda}
  DES_CL_BS1:
    prior:
      min: 1.0
      max: 2.0
    ref:
      dist: norm
      loc: 1.1
      scale: 0.02
    proposal: 0.02
    latex: b_{\mathrm{s}1}
  DES_CL_BS2:
    prior:
      min: -1.0
      max: 1.0
    ref:
      dist: norm
      loc: 0.2
      scale: 0.05
    proposal: 0.05
    latex: b_{\mathrm{s}2}
  DES_CL_R0:
    prior:
      min: 10.0
      max: 60.0
    ref:
      dist: norm
      loc: 30.0
      scale: 3.0
    proposal: 3.0
    latex: r_{0}\,[h^{-1}\mathrm{Mpc}]
  DES_CL_BSZ:
    value: 0.0
    latex: b_{\mathrm{s}z}
likelihood:
  des_cluster.combo_6x2pt_N:
    path: ./projects/des_cluster/tests/frozen/data
    data_file: des_cluster_y6_6x2ptN.dataset
    accuracyboost: 1.0
    internal_accuracyboost: 1.0
    integration_accuracy: 1
    photoz_interpolation_type: 0
    photoz_zmid_convention: 0
    adopt_limber_gs: 1
    adopt_limber_gg: 0
    include_HOD_GX: 0
    include_halo_IA: 0
    lmax: 75000
    kmax_boltzmann: 10.0
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: 0
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    cluster_kernel_mode: 0
    cluster_selection_model: 2
    cluster_ytransform: 1
    cluster_include_ia: 1
    cluster_magnification: -2.0
    cluster_hmf_alpha_mode: 0
    cluster_adopt_limber_cc: 1
    cluster_adopt_limber_cg: 1
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/des_cluster/chains/pca.txt
    external_baryon_suppression: false
    print_datavector: false
    print_datavector_file: ./projects/des_cluster/chains/theory_6x2pt_N.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - As
    - DES_DZ_S1
    - DES_DZ_S2
    - DES_DZ_S3
    - DES_DZ_S4
    - DES_A1_1
    - DES_A1_2
    - DES_A1_3
    - DES_A1_4
    - DES_A2_1
    - DES_A2_2
    - DES_A2_3
    - DES_A2_4
    - DES_BTA_1
    - DES_BTA_2
    - DES_BTA_3
    - DES_BTA_4
    - DES_M1
    - DES_M2
    - DES_M3
    - DES_M4
    - DES_BARYON_Q1
    - DES_BARYON_Q2
    - DES_BARYON_Q3
    - DES_BARYON_Q4
    - DES_DZ_L1
    - DES_DZ_L2
    - DES_DZ_L3
    - DES_DZ_L4
    - DES_DZ_L5
    - DES_DZ_L6
    - DES_B1_1
    - DES_B1_2
    - DES_B1_3
    - DES_B1_4
    - DES_B1_5
    - DES_B1_6
    - DES_B2_1
    - DES_B2_2
    - DES_B2_3
    - DES_B2_4
    - DES_B2_5
    - DES_B2_6
    - DES_BMAG_1
    - DES_BMAG_2
    - DES_BMAG_3
    - DES_BMAG_4
    - DES_BMAG_5
    - DES_BMAG_6
    - DES_DZ2_L1
    - DES_DZ2_L2
    - DES_DZ2_L3
    - DES_DZ2_L4
    - DES_DZ2_L5
    - DES_DZ2_L6
    - DES_PM1
    - DES_PM2
    - DES_PM3
    - DES_PM4
    - DES_PM5
    - DES_PM6
    - DES_CL_LNLAMBDA0
    - DES_CL_A_LAMBDA
    - DES_CL_SIGMA_INT
    - DES_CL_B_LAMBDA
    - DES_CL_BS1
    - DES_CL_BS2
    - DES_CL_R0
    - DES_CL_BSZ
    output_params: []
theory:
  camb:
    version: 1.6.7
    path: ./external_modules/code/CAMB
    speed: 0.3
    stop_at_error: false
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.0
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 12
      kmax: 10
    ignore_obsolete: false
    use_renames: true
    external_primordial_pk: false
    use_non_linear_ratio: false
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      omegan2: omnuh2
    input_params:
    - ns
    - As
    - H0
    - w
    - wa
    - mnu
    - tau
    - omegabh2
    - omegach2
    output_params:
    - omegal
    - sigma8
    - age
    - rdrag
    - yheused
    - omegan2
timing: false
"""
