"""Maintainer tool: (re)create the frozen state the unit tests run on.

Running this REDEFINES what the tests protect, so it refuses to run
without the explicit --overwrite flag. Only run it when a change to
the data vectors, n(z), covariance, examples, or likelihood defaults
is deliberate, and review the printed chi2 values before committing:
they become the new references the tests compare against.

What one run produces, all under tests/ (see cocoa_test_utils for how
the tests consume each piece):

  - frozen/data/: a copy of the files of the CURRENT ../data folder
    the cluster examples read: the synthetic DES Y6-like dataset
    descriptors, joint data vector, covariance, masks, and n(z)
    (DATA_IGNORE below lists what stays out).
  - frozen/EXAMPLE_EVALUATE{1,2}.yaml: snapshots of the current
    examples, kept for humans to diff (the tests never load them).
  - frozen/frozen_config_<example>.py: for each configuration of
    cocoa_test_utils.EXAMPLES, the model is built from the CURRENT
    example yaml, cobaya resolves it against the CURRENT likelihood
    defaults, and the complete resolved configuration is written back
    out as a yaml string, together with the exact evaluation point.
    Writing out every resolved option and parameter is what makes the
    tests independent of later edits to the live files.
  - frozen/reference_chi2.json: one NLA reference chi2 per
    configuration (example1 = 4x2pt + N, example2 = 6x2pt + N),
    computed FROM the frozen modules just written, exactly the way
    the tests will compute them. The shipped data vector is the
    model at the examples' fiducial point, so both sit near zero.
  - manifest_sha256.json: the SHA-256 pin of every frozen file.

Usage (from the Cocoa/ folder, cocoa environment active,
start_cocoa.sh sourced):

    python ./projects/des_cluster/tests/generate_frozen_reference.py --overwrite
"""

import json
import os
import shutil
import sys
import time

# The references must be produced under the same OpenMP thread count
# the tests enforce, and before any cobaya/cosmolike import.
os.environ["OMP_NUM_THREADS"] = "4"

# tests/ is not a package; insert(0, ...) puts it FIRST on the import
# search path so cocoa_test_utils resolves from anywhere
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cocoa_test_utils as u

PROJECT_DIR = os.path.dirname(u.TESTS_DIR)

# Stored inside the frozen configurations as the likelihood data path.
# ROOTDIR-relative on purpose: the frozen modules stay portable across
# machines, and the tests overwrite it with the absolute path anyway.
FROZEN_DATA_RELPATH = "./projects/des_cluster/tests/frozen/data"

# Files of ../data the freeze leaves out: the cluster examples never
# read them, so copying them would only grow the working tree and the
# manifest (the DES-Y3 covariance and the baryon simulation table are
# ~30 MB together). shutil.ignore_patterns matches each entry against
# the file NAME with shell wildcards. The list:
#   .DS_Store                macOS Finder metadata
#   README.md                the description of ../data, not data
#   des_y3_*                 the DES-Y3 3x2pt placeholder data set
#   3x2pt_baseline.mask,     (data vector, covariance, n(z),
#   ones.mask                descriptor) and its two 900-entry masks
#   pca.txt,                 the baryon PCA inputs: the likelihood
#   baryons_logPkR.h5        refuses baryon PCAs with clusters, so the
#                            descriptor's two keys naming them are
#                            never resolved
#   y3_redmapper_counts.txt  the observed DES-Y3 counts, an input of
#                            the covariance script, not of the model
# A new file in ../data is frozen unless it is added here.
DATA_IGNORE = (
    ".DS_Store",
    "README.md",
    "des_y3_*",
    "3x2pt_baseline.mask",
    "ones.mask",
    "pca.txt",
    "baryons_logPkR.h5",
    "y3_redmapper_counts.txt",
)

# The skeleton of one generated frozen-configuration module. The yaml
# goes inside r""" so latex backslashes in parameter labels survive
# (r = raw string: backslashes are kept as typed). The backslash right
# after ''' eats the first newline, so the generated file starts at
# its docstring rather than a blank line. {point} and {yaml} are
# .format placeholders filled in freeze_example.
MODULE_TEMPLATE = '''\
"""AUTO-GENERATED by generate_frozen_reference.py --overwrite ({stamp}).

Frozen, fully expanded cobaya configuration for {example}
(source: {source} resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {point}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
{yaml}
"""
'''


def freeze_example(example, stamp):
    """Write one example's fully expanded frozen-configuration module.

    The expansion works by round trip through cobaya: build the model
    from the live example yaml (letting cobaya merge in the live
    likelihood defaults), then ask the model for its resolved
    configuration with model.info() and store THAT. The resolved form
    lists every option and every parameter explicitly, so the frozen
    module no longer depends on any live default.

    Arguments:
      example = a key of u.EXAMPLES.
      stamp   = the UTC time string written into the module header.

    Returns:
      nothing; frozen/frozen_config_<example>.py is written.

    Raises:
      ValueError when a sampled parameter is neither overridden by the
      example's evaluate block nor given a ref center to fall back on
      (the point would be undefined at that parameter).
    """
    from cobaya.yaml import yaml_load_file, yaml_dump

    cfg = u.EXAMPLES[example]
    live = yaml_load_file(os.path.join(PROJECT_DIR, cfg["provenance"]))
    # The evaluate sampler's override block is the example's fiducial
    # point; keep it before stripping the sampler from the info.
    # dict(...) COPIES the block, so the pop below cannot take it
    # along; pop(key, None) removes a key without erroring when it
    # is already absent.
    override = dict(live["sampler"]["evaluate"]["override"])
    live.pop("sampler", None)
    live.pop("output", None)
    live["debug"] = 30
    live["timing"] = False
    likelihood_block = live["likelihood"][cfg["likelihood"]]
    likelihood_block["path"] = FROZEN_DATA_RELPATH
    # NLA: the only intrinsic-alignment model of the cluster lensing
    # code, pinned here so the frozen configuration cannot inherit
    # another value from an edited example
    likelihood_block["IA_model"] = 0

    # make_model builds the evaluable cobaya Model; building it is
    # what forces cobaya to merge the live likelihood defaults into
    # the configuration
    model = u.make_model(live)
    # model.info() returns the configuration with every default
    # resolved: the complete likelihood option set and the complete
    # parameter list, exactly what must be frozen.
    updated = model.info()
    updated.pop("output", None)
    updated.pop("packages_path", None)
    updated["likelihood"][cfg["likelihood"]]["path"] = FROZEN_DATA_RELPATH

    # The frozen point: the example's override where given, the ref
    # center otherwise. Fallbacks are printed so the maintainer can
    # confirm each one is intended.
    point = {}
    fallback = []
    for name in model.parameterization.sampled_params():
        if name in override:
            point[name] = override[name]
        else:
            ref = updated["params"][name].get("ref")
            # a dict-valued ref describes a distribution; its center
            # "loc" is the fallback. The ternary picks loc for a
            # dict and the plain number otherwise.
            point[name] = ref["loc"] if isinstance(ref, dict) else ref
            fallback.append(name)
            if point[name] is None:
                raise ValueError(
                    f"parameter {name}: not in override and no ref")
    # a list is false when empty: the note prints only when at
    # least one parameter fell back to its ref center
    if fallback:
        print(f"{example}: point uses ref centers for {fallback}", flush=True)

    with open(os.path.join(u.FROZEN_DIR, cfg["frozen_module"]), "w") as f:
        # .format fills each {name} placeholder in the template with
        # the keyword argument of the same name. json.dumps writes
        # the point as JSON text, which doubles as a python literal
        # here; sort_keys makes regenerated modules diff cleanly.
        # yaml_dump returns the configuration as one yaml string and
        # rstrip trims its trailing newlines before the closing """.
        f.write(MODULE_TEMPLATE.format(
            stamp=stamp,
            example=example,
            source=cfg["provenance"],
            point=json.dumps(point, indent=4, sort_keys=True),
            yaml=yaml_dump(updated).rstrip("\n"),
        ))
    print(f"{example}: frozen config expanded to "
          f"{len(updated['params'])} parameters "
          f"({len(live['params'])} in the live example yaml)", flush=True)


def main():
    """Rebuild tests/frozen/ and the manifest from the current project.

    The worker mode comes first: --freeze-one X runs a single
    model-building step and exits. The parent spawns one subprocess
    per step: a process that initializes configurations with
    different data-set dimensions aborts inside cosmolike (see
    cocoa_testing), and one architecture serves every project.

    The parent's steps, in order: refuse without --overwrite; delete
    and recreate frozen/; copy the data and the example snapshots;
    write the expanded frozen-configuration modules; evaluate the
    reference chi2 values from those modules (the same code path the
    tests use); write the reference file; hash everything into the
    manifest. The manifest comes last so it covers every file the
    earlier steps produced. No data vector is generated: the shipped
    one already is the model at the fiducial point (see
    cocoa_test_utils).

    Returns:
      0 on success, 1 when --overwrite was not given (the usage text
      and the refusal reason are printed).
    """
    # `in` scans the argument list for the flag; .index returns the
    # position of its first occurrence, so [index + 1] is the value
    # that follows the flag
    if "--freeze-one" in sys.argv:
        u.require_cocoa_environment()
        example = sys.argv[sys.argv.index("--freeze-one") + 1]
        stamp = sys.argv[sys.argv.index("--stamp") + 1]
        freeze_example(example, stamp)
        return 0
    if "--overwrite" not in sys.argv:
        print(__doc__)
        print("Refusing to run without --overwrite (this redefines the "
              "frozen state every test compares against).")
        return 1
    u.require_cocoa_environment()
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    if os.path.isdir(u.FROZEN_DIR):
        shutil.rmtree(u.FROZEN_DIR)
    os.makedirs(u.FROZEN_DIR)

    print("freezing ../data ...", flush=True)
    # the data copy is what lets users change ../data later without
    # touching the tests; DATA_IGNORE names the files no cluster
    # example reads. ignore_patterns builds the filter function
    # copytree calls in every folder; matching names are skipped (the
    # * spreads the tuple into separate arguments).
    shutil.copytree(os.path.join(PROJECT_DIR, "data"),
                    os.path.join(u.FROZEN_DIR, "data"),
                    ignore=shutil.ignore_patterns(*DATA_IGNORE))
    for cfg in u.EXAMPLES.values():
        shutil.copy2(os.path.join(PROJECT_DIR, cfg["provenance"]),
                     os.path.join(u.FROZEN_DIR, cfg["provenance"]))

    # one worker subprocess per model-building step (see the docstring)
    import subprocess
    # __file__ is this script's own path: each worker re-runs this
    # very file with a mode flag
    self_path = os.path.abspath(__file__)
    # iterating a dict yields its KEYS: each example name in turn.
    # subprocess.run starts the worker (sys.executable = this same
    # python) and waits for it to finish
    for example in u.EXAMPLES:
        completed = subprocess.run(
            [sys.executable, self_path, "--freeze-one", example,
             "--stamp", stamp])
        if completed.returncode != 0:
            raise RuntimeError(f"freeze worker for {example} failed")

    reference = {
        "_meta": {
            "generated_utc": stamp,
            "omp_num_threads": os.environ["OMP_NUM_THREADS"],
            "chi2_tolerance": u.CHI2_TOLERANCE,
        }
    }
    for example in u.EXAMPLES:
        # the "_nla" suffix names the IA model the reference was
        # evaluated with, the key the test modules read
        key = f"{example}_nla"
        t0 = time.time()
        chi2 = u.single_model_chi2(example, False)
        # :.6e = scientific notation with six decimals (the
        # references sit near zero, where fixed decimals would print
        # 0.000000); :.1f = one decimal for the elapsed seconds
        print(f"{key}: chi2 = {chi2:.6e}  ({time.time() - t0:.1f}s)",
              flush=True)
        reference[key] = chi2

    with open(u.REFERENCE_FILE, "w") as f:
        # json.dump writes the table as JSON text into the open
        # file; indent and sort_keys keep the result stable and
        # diffable, and the extra write adds the final newline text
        # files end with (load_reference round-trips it back)
        json.dump(reference, f, indent=2, sort_keys=True)
        f.write("\n")

    # compute_manifest returns {relative path: sha256} for every file
    # now under frozen/; writing it LAST means it covers every file
    # the steps above produced
    manifest = {
        "_comment": "SHA-256 of every file under tests/frozen/; verified by "
                    "every test before evaluating anything.",
        "files": u.compute_manifest(),
    }
    with open(u.MANIFEST_FILE, "w") as f:
        # the same stable JSON write as the reference file above
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"manifest: {len(manifest['files'])} files pinned")
    return 0


# __name__ is "__main__" only when this file runs directly as a
# script; sys.exit(main()) hands main's return value to the shell
# as the exit code (0 = success)
if __name__ == "__main__":
    sys.exit(main())
